pipeline {
   agent any

   tools {
      // Install the Maven version configured as "M3" and add it to the path.
      maven "maven"
   }

   stages {
      stage('Build') {
         steps {
            // Get some code from a GitHub repository
            git 'https://github.com/HugoGlz/mvn-spring-restful.git'
            sh 'mvn -B -DskipTests clean package'
         }
      }
      
      stage('Test'){
          steps {
              sh 'mvn test'
          }
          post {
              always {
                  junit 'target/surefire-reports/*.xml'
              }
          }
      }
   }
   
   post {
       success {
           script {
                currentBuild.result = 'SUCCESS'
           }
       }
       always {
          step([$class: 'Mailer',
            /*notifyEveryUnstableBuild: true,*/
            recipients: "hugo.java21@gmail.com",
            sendToIndividuals: true])
        }
   }
}